Repository cloud-native-toolkit/terraform-gitops-pull-secret, pull requests merged in 2022-01, with the labels that each got.

#1 Implements logic to generate pull secret
  .github/scripts/validate-deploy.sh
  .github/workflows/verify.yaml
  README.md
  main.tf
  outputs.tf
  scripts/create-yaml.sh
  test/stages/stage1-cluster.tf
  test/stages/stage1-gitops-bootstrap.tf
  test/stages/stage1-gitops.tf
  test/stages/stage1-olm.tf
  test/stages/stage1-resource-group.tf
  test/stages/stage2-pull-secret.tf
  test/stages/stage3-outputs.tf
  test/stages/variables.tf
  variables.tf
Labels: enhancement, major

#2 add support for secret name
  .github/scripts/validate-deploy.sh
  .github/workflows/publish-assets.yaml
  .github/workflows/verify.yaml
  main.tf
  test/stages/stage2-pull-secret.tf
  test/stages/stage3-outputs.tf
  variables.tf
  version.tf
Labels: enhancement, minor

#3 Sets docker_username test value for error checking
  main.tf
  test/stages/stage2-pull-secret.tf
Labels: bug, patch

#4 Adds create_webhook flag to test
  test/stages/stage1-gitops-bootstrap.tf
Labels: patch, chore

#5 Adds kubeseal_namespace test variable
  test/stages/stage1-gitops-bootstrap.tf
  test/stages/variables.tf
Labels: bug, patch
